### ISSUE TITLE
Support reading key from var, rather than file

### ISSUE THREAD

**Issue by conorsch** [infOpen/ansible-role-aptly#9]
The current implementation uses `copy` to transfer the repo private key from the Ansible controller, which means the private key must exist on plaintext on the Ansible controller. I'd much rather store the private key content in an encrypted vars file and have the role write it to the remote host.

**Comment by conorsch** [comment]
The cleanest approach to support the existing behavior of the role is to add a new var `aptly_custom_gpg_key_content` and use it instead of `aptly_custom_gpg_key_file` if specified. That way, both the `copy` method and the var-based method will work.

**Comment by inka** [comment]
since ansible v2.1 _copy_ is doing a transparent decrypt of vault encrypted files. so just encrypt your private key and that's it. pls close this issue.

**Comment by achaussier** [comment]
Yes, I close it.
